spring:
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: never # Disable SQL initialization scripts
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true

stripe:
  secret:
    key: "sk_test_51QwmaiPrlrRfBw5poWTCLViYs4omAuLFYw2nxjXQAZaNlXFcGh5GK7JSWdBSEvrPvsrhAXpJ1cgcYM4vb1m1ZbuK00wjYwLacc"

electricity-map:
  credentials:
    - countryCode: "GB"
      token: VCyrqfmKZlIHOhXxW3Gu
    - countryCode: "FR"
      token: twSM0Q2rLNgp0jZlh520
    - countryCode: "TH"
      token: e2lyFnJUmL4AZ6fPJ7Sf
    - countryCode: "ZA"
      token: I2GDiqQULbIqNPTXlLYs
    - countryCode: "CA"
      token: WInPiA3w3DwlnCIE91ej

# Development-specific configurations
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.example.server: DEBUG
