spring:
  application:
    name: solar-offset
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/solaroffset?serverTimezone=UTC&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    username: root
    password: Shreyas@123
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/init.sql
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 234686151907-h0egb9h34beugoudlrffovu95nkt4a10.apps.googleusercontent.com
            client-secret: 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
  mail:
      host: smtp.gmail.com
      port: 587
      username: managesyntaxsquad@gmail.com
      password: haxm eebh qcit ktvz    # Google App Password
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

server:
  port: 8000

logging:
  level:
    org.hibernate.SQL: DEBUG
jwt:
  secret:
    key: "x4p9d7f8g2h1k6q3w7e5r9t2y6u7i8o0l1a2b3c4d5e6f7g8"
stripe:
  secret:
    key: "sk_test_51QwmaiPrlrRfBw5poWTCLViYs4omAuLFYw2nxjXQAZaNlXFcGh5GK7JSWdBSEvrPvsrhAXpJ1cgcYM4vb1m1ZbuK00wjYwLacc"
electricity-map:
  credentials:
    - countryCode: "GB"
      token: VCyrqfmKZlIHOhXxW3Gu
    - countryCode: "FR"
      token: twSM0Q2rLNgp0jZlh520
    - countryCode: "TH"
      token: e2lyFnJUmL4AZ6fPJ7Sf
    - countryCode: "ZA"
      token: I2GDiqQULbIqNPTXlLYs
    - countryCode: "CA"
      token: WInPiA3w3DwlnCIE91ej
