electricity-map:
  credentials:
    - countryCode: "GB"
      token: VCyrqfmKZlIHOhXxW3Gu
    - countryCode: "FR"
      token: twSM0Q2rLNgp0jZlh520
    - countryCode: "NO"
      token: e2lyFnJUmL4AZ6fPJ7Sf
    - countryCode: "ZA"
      token: I2GDiqQULbIqNPTXlLYs
    - countryCode: "CA"
      token: WInPiA3w3DwlnCIE91ej
